excel:
  path: "/Users/ryu/mojolll/"
  fileName: "학교개황(20230228 기준).xls"


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mojolll?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: hwryu990927!


  security:
    user:
      name: user
      password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
    defer-datasource-initialization: true

  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 6379
    host: 127.0.0.1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

