server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: oauth2-client-app
            clientSecret: AbiFqNHhoWILjexz74QPZfumFgTYGhNF
            clientName: oauth2-client-app
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: client_secret_basic
            scope: openid,profile,email
        provider:
          keycloak:
            authorizationUri: http://0.0.0.0:8080/realms/oauth2/protocol/openid-connect/auth
            tokenUri: http://0.0.0.0:8080/realms/oauth2/protocol/openid-connect/token
            issuerUri: http://0.0.0.0:8080/realms/oauth2
            userInfoUri: http://0.0.0.0:8080/realms/oauth2/protocol/openid-connect/userinfo
            jwkSetUri: http://0.0.0.0:8080/realms/oauth2/protocol/openid-connect/certs
            userNameAttribute: preferred_username

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mojolll?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: hwryu990927!

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  security:
#    user:
#      name: user
#      password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
    defer-datasource-initialization: true


  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 6379
    host: 127.0.0.1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
