#spring:
#  profiles:
#    active: local
#---
server:
  port: 8084

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    oauth2:
      client:

        registration:
          google:
            client-id: 446101020262-1i0bbmetf6ug3seb6krubsa85po28hp5.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email

          github:
            client-id: 4c3b075956b10ec02d40
            client-secret: 42a8162043be67d747884a5aa5dc826867ec4bab
#            authorization-grant-type: authorization_code
#            client-name: cojople
#            redirect-uri: http://localhost:8081/login/oauth2/code/github
            scope: profile,email

          kakao:
            client-id: 9b3f075daee50d35e66e866a4f9376a2
            client-secret: 0hpHABl7jp4V9BlulcP3w4pHmWZZk55A
            client-name: cojople
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email,openid


        provider:
          #https://kauth.kakao.com/.well-known/openid-configuration
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            issuer-uri: https://kauth.kakao.com
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: sub


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.130.222:3306/project?serverTimezone=UTC&characterEncoding=UTF-8
    username: uhanuu
    password: 1234

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  security:
#    user:
#      name: user
#      password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
    defer-datasource-initialization: true


  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 6379
    host: 52.79.130.222

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
